* Шаблон статьи                                                      :ignore:
# some information

#+setupfile: ../math/user.org
#+LATEX_HEADER: \usepackage{translator}
#+LATEX_HEADER: \uselanguage{Russian}
#+LATEX_HEADER: \languagepath{Russian}

#+setupfile: ../theorems/plain.org

# #+setupfile: ../org_mode_setupfiles/article/gost.org
# #+setupfile: ../org_mode_setupfiles/article/plain/ru.org
# #+setupfile: ../org_mode_setupfiles/fontset/msword.org
# #+setupfile: ../org_mode_setupfiles/fontset/cyrillic_modern.org
# #+setupfile: ../org_mode_setupfiles/fontset/tex_gyre_termes.org
# #+setupfile: ../org_mode_setupfiles/math/ru.org
# #+setupfile: ../org_mode_setupfiles/theorems/plain.org
# #+setupfile: ../org_mode_setupfiles/fontset/xcharter.org
# #+LATEX_CLASS_OPTIONS: [12pt]
# #+LATEX_HEADER_EXTRA: \geometry{left=2.5cm, right=2cm, top=2cm, bottom=2cm}
# #+latex_header_extra: \setstretch{1.25}
# #+LATEX_HEADER: \thispagestyle{empty}
#+LANGUAGE: ru
#+OPTIONS: tags:nil
#+TAGS: export

#+title: Некоторые свойства кодов квадратичных отношений, его использование в задаче поиска слов небольшого веса в коде
** Введение                                                           :export:
Написать введение \( \set{A}{B} \)

** Основные термины и определения                                     :export:

Если \( \gfq \)\nbsp{}--- конечное поле из \( q \) элементов, то для произвольного натурального числа \( n \) через \( \gfq^{n} \) обозначим линейное пространство векторов длины \( n \) над полем \( \gfq \).
Тогда линейным блоковым кодом длины \( n \) над полем \( \gfq \) (или просто \( [n]_{q} \)-кодом) называется произвольное линейное подпространство \(\code\) пространства \( \gfq^{n}\).

Линейный код \( \code \) как подпространство конечномерного пространства имеет некоторую размерность \( k \), которая называется размерностью кода \( \code \).
Линейный код длины \( n \) и размерности \( k \) над полем \( \gfq \) будем называть \( [n,k]_{q} \)-кодом.
Векторы \( \cect\in \gfq^{n} \), лежащие в \( \code \) называются кодовыми словами (или просто словами) \( \code \).

В дальнейшем для произвольных натуральных чисел \( k \) и \( n \) через \( \gfq^{k\times n} \) будем обозначать множество всех \( (k\times n) \)-матриц над полем \( \gfq \).
Матрица \( \gatr_{\code}\in \gfq^{k\times n} \), у которой строки являются базисными векторами \( [n,k]_{q} \)-кода \( \code \), называется порождающей матрицей кода \( \code \).

Матрицы \( \gatr_{1},\gatr_{2}\in \gfq^{k\times n} \) порождают один и тот же код \( \code \), если и только если для некоторой невырожденной \( (k\times k) \)-матрицы \( \aatr \) с элементами из поля \( \gfq \) (т.е. \( \aatr\in \gl[q](k) \)) выполняется равенство \( \gatr_{2} = \aatr\cdot \gatr_{1}. \)

Для \( [n,k]_{q} \)-кода \( \code \) можно определить дуальный код \( \dual{\code} \) как множество всех векторов \( \xect\in \gfq^{n} \), которые ортогональны каждому слову \( \code \), т.е.
\[ \dual{\code} = \set{\xect\in \gfq^{n}}{\Angle{\xect,\yect}\bydef \xect\cdot \tran{\cect} = 0\quad\forall\; \cect\in\code}. \]
Ясно, что \( \dual{\code} \) является \( [n,n-k]_{q} \)-кодом.
Его порождающая \( ((n-k)\times n) \)-матрица \( \hatr \) называется проверочной матрицей кода \( \code \).
Несложно увидеть, что \( \cect\in\code \), если и только если \( \hatr\cdot\tran{\cect}=\vect[0]. \)

Весом Хемминга (или просто весом) вектора \( \xect\in \gfq^{n} \) называется целое число \( \wt{\xect} \), равное количеству его ненулевых координат.
Минимальным расстоянием \( d_{\code} \) кода \( \code \) будем называть минимальный вес ненулевых кодовых слов \( \code \), т.е. если \( \code \)\nbsp{}--- \( [n,k]_{q} \)-код, то \( d_{\code}=\min\limits_{\begin{subarray}{c}\cect\in \code\\ \wt{\cect}\neq 0\end{subarray}}\wt{\cect}. \)
Если \( [n,k]_{q} \)-код \( \code \) имеет минимальное расстояние \( d \), то такой код будем называть \( [n,k,d]_{q} \)-кодом.

Справедливо следующее утверждение (см.\nbsp{}[cite:@macwilliams1979]).

#+name: prop:singlton
#+attr_latex: :options [Граница Синглтона]
#+begin_proposition
Для любого \( [n,k,d]_{q} \)-кода выполняется неравенство \( d\le n-k+1. \)
#+end_proposition

С каждым вектором \( \xect\in\gfq^n \) можно связать множество \( \Supp{x} \) номеров его ненулевых координат, которое в дальнейшем будем называть носителем вектора \( \xect \).
Получается, что если \( \nat\bydef\set{1,2,\dotsc,n}\), то
\[ \Supp{\xect=\sequence{x_1,x_2,\dotsc,x_{n}}}\bydef\set{i\in\nat}{x_{i}\neq 0}. \]

Для произвольного множества векторов \( U\subseteq \gfq^{n} \) определим носитель \( \Supp{U} \) этого множества как объединение носителей векторов \( \xect \), принадлежащих \( U \), т.е.
\[ \Supp{U}=\bigcup_{\xect\in U}\Supp{\xect}. \]
Таким образом, можно говорить о носителе \( \Supp{\code} \) кода \( \code \).
Если для кода \( \code \) выполняется равенство \( \Supp{\xect}=\nat \), то \( \code \) будем называть кодом с полным носителем.
Фактически код имеет полный носитель, если и только если его порождающая матрица не имеет нулевых столбцов, это также эквивалентно тому, что минимальное расстояние \( d_{\dual{\code}} \) дуального кода \( \dual{\code} \) не меньше двух: \( d_{\dual{\code}}\ge 2. \)

** Произведение Шура--Адамара и квадратичные формы и код квадратичных отношений :export:

Произведением Шура--Адамара (произведение Шура, произведением Адамара или покомпонентным произведением) \( [n]_q \)-кодов  \( \code \) и \( \bode \) будем называть \( [n]_q \)-код  \( \aode=\code\hprod\bode \), который состоит из линейной оболочки векторов \[ \set{\cect\hprod \bect = (c_1,\ldots, c_n)\hprod (b_1,\dotsc,  b_n) \bydef (c_1\cdot b_1,\dotsc, c_n\cdot b_n)}{\cect\in\code,\ \bect\in\bode}. \]

Если \( s\in\NN \), то степенью Шура--Адамара кода \( \code \) будем называть код
\[ \code^{\hprod s}=\underbrace{\code\hprod\code\hprod\ldots\hprod\code}_{s\text{ раз }}. \]
Тогда квадратом Шура--Адамара кода \( \code \) называется код \(\code^{\hprod 2}=\code\hprod \code \).
Для любого \( [n,k]_{q} \)-кода \( \code \) выполняется неравенство \( \dim \code^{\hprod 2}\le\min\left(n,\frac{k(k+1)}{2}\right). \)

Обозначим через \(\gfq^{\textrm{hom}}[x_{1},x_2,\ldots,x_{k}]_{2}\) линейное пространство квадратичных форм над полем \( \gfq \) от переменных \( x_1, x_2, \dotsc, x_{k} \), т.е. \( \gfq^{\textrm{hom}}[x_1, x_2, \dotsc, x_k]_{2} \) состоит из всех возможных многочленов
\[ Q(x_{1}, x_2, \dotsc, x_{k}) = \sum_{1\le i\le j\le k}a_{i,j}x_{i}x_{j},\ a_{i,j}\in \gfq. \]

Пусть \(\gatr \in \gfq^{k \times n} \).
Определим отображение
\[ \ell_{\gatr}:\ \gfq^{\textrm{hom}}[x_{1},x_2,\ldots,x_{k}]_{2} \rightarrow \gfq^{n}. \]
Если \( \gect_i^{\top}= \sequence{g_{i,1}, g_{i,2},  \ldots, g_{i,k}}^{\top}\)\nbsp{}--- столбец с номером \( i \), \( 1\le i\le n\), матрицы \( \gatr \), то
\[ \ell_{\gatr}: Q(x_1,x_2, \ldots, x_{k}) \rightarrow Q(\gatr)\bydef \sequence{Q(\gect_1), Q(\gect_2), \ldots, Q(\gect_{n})}. \]
Тогда если \( \gatr \) порождает код \( \code \), то  \( \im \ell_{\gatr} = \code^{\hprod 2} \) (см., например,\nbsp{}[cite:@randriambololona2014]).
А значит для любой матрицы \( \aatr\in \gl[q](k) \) выполняется равенство \( \im \ell_{\aatr\cdot \gatr} = \im \ell_{\gatr}. \)

Для каждой матрицы \( \gatr\in\gfq^{k\times n} \) помимо образа отображения \( \ell_{\gatr} \) можно рассмотреть его ядро \( \ker \ell_{\gatr} \), т.е.
\( \ker \ell_{\gatr} = \set{Q\in \gfq^{\textrm{hom}}[x_1,x_2, \ldots, x_k]_{2}}{Q(\gatr)=\vect[0]}. \)
В дальнейшем \( \ker\ell_{\gatr} \) будем называть ядром Шура--Адамара кода \( \code \).

С \( \ker\ell_{\gatr} \) можно связать другой линейный код\nbsp{}[cite:@Couvreur_2023].
Если
\[ \coeff(Q)\bydef \sequence{a_{1,1}, a_{1,2}, \ldots, a_{1,k}, a_{2,2}, \ldots, a_{2,k}, \ldots, a_{k,k}}\in \gfq^{\frac{k(k+1)}{2}}, \]
то код \( \qode_{\gatr} \) состоит векторов \( \coeff(Q) \), \( Q\in \ker \ell_{\gatr} \).
Ясно, что \( \qode_{\gatr} \) является \( [k(k+1)/2, k(k+1)/2-k^{\hprod 2}]_{q} \)-кодом.
Здесь через \( k^{\hprod 2} \) обозначена размерность квадрата Шура--Адамара кода, совпадающего с линейной оболочкой строк матрицы \( \gatr \).

Образ линейного оператора \( \ell_{\gatr} \) не будет зависеть от выбора порождающей матрицы \( \gatr \) кода \( \code \), поэтому можно говорить о том, что \( \im \ell_{\gatr} \) однозначно определяется по коду \( \code \).
Однако ядро \( \ell_{\gatr} \) будет зависеть от выбора порождающей матрицы, поэтому код \( \qode_{\gatr} \) является характеристикой не самого кода \( \code \), а его порождающей матрицы и в общем случае по \( \code \) определены не однозначно.

#+name: def:ker-hadamard
#+begin_definition
Ядром Шура--Адамара кода \( \code \) будем называть множество ядер \( \ker\ell_{\gatr} \) отображений \( \ell_{\gatr} \) для всех возможных порождающих матриц \( \gatr \).
При этом если мы будем говорить, что какое-то свойство \( A \) выполнено для ядра Шура--Адамара кода \( \code \), то это будет означать, что свойство \( A \) выполняется для всех \( \ker\ell_{\gatr} \) какую бы порождающую матрицу \( \gatr \) кода \( \code \) мы не выбрали.
#+end_definition

Далее, помимо пространства квадратичных форм рассмотрим пространство линейных форм \( \gfq^{\textrm{hom}}[x_1,x_2,\dotsc,x_k]_{1} \), которое состоит из однородных многочленов \( L(x_1,x_2,\dotsc, x_k) \) степени \( 1 \) от переменных \( x_1,x_2,\dotsc,x_k \) над полем \( \gfq \), т.е.
\[ L(x_1,x_2,\dotsc,x_k)=a_1x_1+a_2x_2+\dotsb+a_k x_k. \]

В работе нас будут интересовать квадратичные формы \( Q\in \ker\ell_{\gatr} \), которые можно разложить на линейные множители, т.е. для которых существуют такие \( L_{1}, L_{2}\in\gfq^{\textrm{hom}}[x_1,x_2,\dotsc,x_k]_{1} \), что
\[ Q(x_1,x_2,\dotsc, x_{k})=L_{1}(x_1,x_2,\dotsc,x_k)\cdot L_2(x_1,x_2,\dotsc,x_k). \]

#+name: def:quadratic-decomp
#+begin_definition
Квадратичную форму \( Q\in\gfq^{\textrm{hom}}[x_1,x_2,\dotsc,x_k]_{2} \) будем называть \emph{разложимой на линейные множители} (или просто \emph{разложимой}), если существуют такие *различные* \( L_{1},L_{2}\in\gfq^{\textrm{hom}}[x_{1},x_2,\dotsc, x_k]_1 \), что \( Q=L_{1}\cdot L_{2} \).
#+end_definition

Каждой квадратичной форме \( Q \) можно поставить в соответствие ее матрицу \( \matr_{Q}=(m_{i,j})\in \gfq^{k\times k} \) следующим образом:
\[ m_{i,j}=\begin{cases}a_{i,j},&\text{если }1\le i\le j\le k;\\
0,&\text{иначе}.\end{cases} \]
Тогда можно рассмотреть симметрическую матрицу \( \batr_{Q}=\matr_{Q}+\tran{\matr}_{Q}, \) которая фактически является матрицей билинейной формы, соответствующей квадратичной форме \( Q \).
Если характеристика поля \( \gfq \) отлична от двух, то между квадратичными формами и их билинейными формами имеется взаимно однозначное соответствие, которое распространяется и на соответствие \( Q \leftrightarrow \batr_{Q} \).
В случае, когда поле \( \gfq \) имеет характеристику \( 2 \) можно говорить только о биективном соответствии между билинейными формами и смежными классами по \( \gfq^{\textrm{hom}}[x_1,x_2,\dotsc,x_k]_{1} \).

Несложно понять, что если квадратичная форма \( Q \) представима в виде \( Q=L_{1}\cdot L_{2} \), то ранг матрицы \( \batr_{Q} \) не больше \( 2 \).

Во-первых, таких квадратичных форм в \( \ker \ell_{\gatr} \) может не быть, поэтому необходимо изучить условия, при которых такие формы существуют.
Во-вторых, нас будет интересовать алгебраическая структура делителей \( L_{1} \) и \( L_{2} \) таких квадратичных форм.

** Условия существования в ядре отображения \( \ker\ell_{\gatr} \) квадратичных форм ранга не выше \( 2 \). :export:

Отображение \( \ell_{\gatr} \) можно распространить на множество линейных форм, а также в общем на множество всех полиномов \( \gfq[x_{1},x_2,\dotsc,x_{k}] \).
Так если \( F\in \gfq[x_1,x_2,\dotsc,x_k] \) и \( \gatr \) некоторая порождающая \( (k\times n) \)-матрица \( [n,k]_{q} \)-кода \( \code \), то отображение \( \overline{\ell}_{\gatr}: \gfq[x_1,x_2,\dotsc,x_k]\rightarrow \gfq^{n} \) ставит в соответствие вектор
\[ \sequence{F(\gect^{(1)}), F(\gect^{(2)}), \dotsc,F(\gect^{(n)})}, \]
здесь \( \gect^{(j)}\in \gfq^{k} \)\nbsp{}--- вектор, равный столбцу с номером \( j \), \( j=1,2,\dotsc, n \), матрицы \( \gatr \).
Таким образом, \( \overline{\ell}_{\gatr}(F) \) является вектором значений полинома \( F \) на столбцах матрицы \( \gatr \).
А поэтому для любых \( F_{1},F_{2}\in \gfq[x_1,x_2,\dotsc, x_k] \) выполняется равенство
#+name: eq:mul-l
\begin{equation}
\overline{\ell}_{\gatr}(F_{1}\cdot F_{2})=\overline{\ell}_{\gatr}(F_{1})\cdot \overline{\ell}_{\gatr}(F_2).
\end{equation}

Ясно, что сужение \( \overline{\ell}_{\gatr} \) на множество квадратичных форм является отображением \( \ell_{\gatr} \).
Рассмотрим также сужение \( \widetilde{\ell}_{\gatr}\bydef\left.\overline{\ell}_{\gatr}\right\vert_{\gfq^{\textrm{hom}}[x_1,x_2,\dotsc, x_{k}]_{1}} \) на множество линейных форм \( \gfq^{\textrm{hom}}[x_1,x_2,\dotsc, x_{k}]_{1}. \)
Таким образом, \( \widetilde{\ell}_{\gatr}:\gfq^{\textrm{hom}}[x_1,x_2,\dotsc,x_k]_{1}\rightarrow \gfq^{n} \) и если \( L\in\gfq^{\textrm{hom}}[x_1,x_2,\dotsc,x_k]_{1} \), то \( \widetilde{\ell}_{\gatr}(L) = \overline{\ell}_{\gatr}(L). \)

Пусть \( L=a_1x_1+a_2x_2+\dotsb+a_kx_k \) и \( \gect_{(i)} \)\nbsp{}\nbsp{}--- строка с номером \( i \), \( i=1,2,\dotsc,k \), матрицы \( \gatr \), то несложно увидеть, что
\[ \widetilde{\ell}_{\gatr}(L) = a_{1} \gect_{(1)} + a_2\gect_{(2)}+\dotsc+a_k\gect_{(k)}=\coeff(L)\cdot \gatr,\]
т.е. \( \widetilde{\ell}_{\gatr}(L)\in \code \) для любого \( L\in\gfq^{\textrm{hom}}[x_1,x_2,\dotsc, x_k]_{1} \), поэтому \( \im \widetilde{\ell}_{\gatr} = \code \).

Значит если \( Q = L_{1}\cdot L_{2} \), \( L_{1},L_{2}\in\gfq^{\textrm{hom}}[x_{1},x_2,\dotsc, x_k]_{1} \), то с учетом равенства\nbsp{}[[eq:mul-l]] справедлива цепочка неравенств
\[ \ell_{\gatr}(Q)=\overline{\ell}_{\gatr}(L_{1}\cdot L_{1}) = \overline{\ell}_{\gatr}(L_{1})\cdot \overline{\ell}_{\gatr}(L_{2})=\widetilde{\ell}_{\gatr}(L_{1})\cdot \widetilde{\ell}_{\gatr}(L_2). \]

Несложно доказать следующее утверждение.
#+name: prop:fact-via-supp
#+begin_proposition
Если \( L_{1},L_{2}\in\gfq^{\mathrm{hom}}[x_1,x_2,\dotsc,x_k]_{1} \), то равенство \( L_{1}\cdot L_{2} =0 \) выполнено, если и только если \( \Supp{\widetilde{\ell}_{\gatr}(L_{1})}\cap \Supp{\widetilde{\ell}_{\gatr}(L_{2})}=\emptyset, \) т.е. множество ненулевых координат векторов \( \widetilde{\ell}_{\gatr}(L_{1}) \) и \( \widetilde{\ell}_{\gatr}(L_{2}) \) не пересекаются.
#+end_proposition

Теперь в качестве следствия из\nbsp{}[[prop:fact-via-supp]] получим следующее.
#+name: prop:binary-codes
#+begin_proposition
Если двоичный \( [n,k]_{2} \)-код \( \code \) с порождающей матрицей \( \gatr \) содержит вектор \( \vect[1]^{n} \), состоящий из одних единиц, и \( k\ge 2 \), то \( \ker\ell_{\gatr} \) содержит разложимые квадратичные формы \( Q \).
#+end_proposition
#+begin_proof
Для доказательства утверждения достаточно заметить, что если в \( \code \) имеется вектор \( \vect[1]^{n} \) и размерность \( \code \) не меньше \( 2 \), то в \( \code \) найдется еще хотя бы один вектор \( \cect\neq \vect[1]^{n} \).

Значит можно рассмотреть векторы \( \cect_{1}=\cect \) и \( \cect_{2}=\cect+\vect[1]^{n} \), \( \cect_{1}\neq \cect_{2} \).

Тогда в двоичном случае \( \cect_{1}\cdot \cect_{2}=\vect[0] \) и, поэтому, если \( \cect_{1}=\widetilde{\ell}_{\gatr}(L_{1}) \) и \( \cect_{2}=\widetilde{\ell}_{\gatr}
(L_{2}) \), то, во-первых, \( L_{1}\neq L_{2} \), а, во-вторых, на основании утверждения\nbsp{}[[prop:fact-via-supp]] верно включение \( Q=L_{1}\cdot L_{2}\in\ker\ell_{\gatr} \), так как по построению \( \Supp{\cect_{1}}\cap\Supp{\cect_{2}} = \emptyset \).
#+end_proof

Из утверждения\nbsp{}[[prop:binary-codes]] следует, что если код \( \code \) выбирается случайно и равновероятно из множества всех \( [n,k]_{2} \)-кодов, то в ядре Шура--Адамара этого кода будет квадратичная форма ранга не выше \( 2 \) с вероятностью \( 1/2 \), что противоречит утверждению\nbsp{}10 работы \nbsp{}[cite:@Couvreur_2023] (см. приложения C2, стр.45).
Там говорится,
что наличие таких форм возможно только с пренебрежимо малой вероятностью.
Таким образом, результаты работы\nbsp{}[cite:@Couvreur_2023], как минимум, требуют уточнения.

Продолжим характеризацию кодов, в ядре Шура--Адамара которых имеются разложимые квадратичные формы.

#+name: def:inform-set
#+begin_definition
Пусть \( I \subseteq \nat \).
Традиционно множество \( I \) называется информационным окном или информационным множеством \( [n,k]_{q} \)-кода \( \code \) с порождающей матрицей \( \gatr \), если \( |I|=k \) и подматрица \( \gatr\vert_{I} \), составленная из столбцов \( \gatr \) с номерами из \( I \), является невырожденной.
#+end_definition

Если \( T\subseteq \nat \) и \( \vect=\sequence{v_1,v_2,\dotsc,v_n}\in \gfq^{n} \), то через \( \vect\vert_{T} \) обозначим подвектор вектора \( \vect \), составленный из координат с номерами из множества \( T \), т.е. \( \vect\vert_{T}=\sequence{v_{i},\ i\in T}\in \gfq^{n-|T|}\).

Далее определим еще два вектора: \( \vect_{\setminus T} \) и \( \vect_{T} \).
Вектор \( \vect_{\setminus T}\in \gfq^{n-|T|} \) имеет длину \( n-|T| \) и состоит из тех координат вектора \( \vect \), номера которых не лежат во множестве \( T \), т.е. \( \vect_{\setminus T}=\vect\vert_{\nat\setminus T} \) и он получается из \( \vect \) удалением координат с номерами из множества \( T \).
Вектор \( \vect_{T}\in\gfq^{n} \) имеет ту же длину, что \( \vect \), и получается из \( \vect \) обнулением координат, имеющих номера из множества \( T \).
Получается, что если \( \vect_{T}=\sequence{u_{1},u_{2},\dotsc,u_{n}} \), то для всех \( i\in \nat\setminus T \) выполняется равенство \( u_{i}=v_{i} \), а для \( i\in T \)\nbsp{}--- равенство \( u_{i}=0\).

#+name: def:punct-code
#+begin_definition
Для \( [n]_{q} \)-кода \( \code \) и множества \( T\subseteq \nat \) через \( \code_{T} \) обозначим \( [n]_{q} \)-код, состоящий из \( \cect_{T} \) для всех \( \cect\in \code \).
Назовем \( T \)-выколотым (или просто выколотым) кодом \( [n-|T|]_{q} \)-код \( \code_{\setminus T} \), который состоит из векторов \( \cect_{\setminus T} \) для всех \( \cect\in \code \).
И, наконец, \( T \)-укороченным (или просто укороченным) кодом назовем \( [n]_{q} \)-код \( \code^{T}=\code_{T}\cap\code \).
#+end_definition

Легко понять, что если \( T\neq \nat \), то \( \code_{\setminus T} \) не является подкодом кода \( \code \).
Код \( \code_{T} \) будет подкодом кода \( \code \), если и только если \( T\cap\Supp{\code} =\emptyset\).
И \( \code^{T} \)\nbsp{}--- подкод \( \code \) по построению.

Используя несложные соображения из линейной алгебры можно доказать следующее.
#+name: prop:inf-set
#+begin_proposition
Множество \( I\subseteq \nat \), \( |I|=k \), является информационным для \( [n,k]_{q} \)-кода \( \code \), если и только выполнено одно из условий:
1. \( \code^{I}=\set{\vect[0]^{n}}. \)
2. для любого \( \cect\in\code \) из равенства \( \cect_{\setminus (\nat\setminus I)}=\vect[0]^{k} \) следует, что \( \cect=\vect[0]^{n}  \), т.е. для любого ненулевого кодового слова \( \cect \) его подвектор, состоящий из координат с номерами из \( I \), не равен нулевому вектору.
#+end_proposition

Зададимся вопросом при каком условии для заданной линейной формы \( L\in \gfq^{\textrm{hom}}[x_1,x_2,\dotsc,x_k]_{1} \) существует такая линейная форма \( K\in\gfq^{\textrm{hom}}[x_1,x_2,\dotsc,x_k]_{1} \), что \( Q=L\cdot K \) принадлежит \( \ker\ell_{\gatr} \).

Докажем следующее утверждение.

#+name: prop:criteria-l
#+begin_proposition
Пусть \( L\in\gfq^{\textrm{hom}}[x_1,x_2,\dotsc, x_k]_{1} \) и \( \cect=\widetilde{\ell}_{\gatr}(L) \).
Тогда существует такая линейная форма \( K\in\gfq^{\textrm{hom}}[x_{1},x_2,\dotsc, x_k]_{1} \), что \( K\neq 0 \) и \( Q=L\cdot K\in \ker\ell_{\gatr} \), если и только если \( \Supp{\cect} \) не содержит информационное множество кода \( \code \), порождаемого \( \gatr \).
#+end_proposition
#+begin_proof
Пусть \( T=\Supp{\cect} \).

Если существует такая ненулевая форма \( K\in\gfq^{\textrm{hom}}[x_1,x_2,\dots,x_k]_{1} \), что \( Q=K\cdot L\in\ker\ell_{\gatr} \), то на основании утверждения\nbsp{}[[prop:fact-via-supp]] следует выполнение равенства \( T\cap\Supp{\widetilde{\ell}_{\gatr}(K)}=\emptyset. \)
А значит \( \bect=\widetilde{\ell}_{\gatr}(K) \) принадлежит коду \( \code^{T} \) по построению последнего.
По условию \( K\neq 0 \), что эквивалентно неравенству \( \bect\neq \vect[0] \).
Поэтому в этом случае код \( \code^{T} \) будет содержать ненулевое кодовое слово.

Для произвольного подмножества \( S \) множества \( T \) справедливо включение \( \code^{T}\subseteq \code^{S} \), поэтому код \( \code^{S} \) для любого подмножества \( S\subseteq T \) будет содержать ненулевой вектор.
Но тогда применяя к \( S \) пункт 1 утверждения\nbsp[[prop:inf-set]] получим, что все эти подмножества \( S \) не являются информационным множеством кода \( \code \), т.е. \( T \) не содержит информационное множество этого кода.

Обратно.
Пусть \( T \) не содержит информационное множество \( \code \), тогда опять из утверждения\nbsp{}[[prop:inf-set]] следует наличие в коде \( \code^{T} \) ненулевого кодового слова \( \bect \).
Получается, что по определению \( \code^{T} \) верно равенство \( T\cap\Supp{\bect}=\emptyset \), поэтому из утверждения\nbsp{}[[prop:fact-via-supp]] для \( K \), заданной равенством \(\widehat{\ell}_{\gatr}(K)\), выполняется условие \( Q=L\cdot K\ker\ell_{\gatr} \).
С другой стороны, так как \(\bect\neq\vect[0] \), то \( K \) не равна тождественно нулю.
#+end_proof

Для каждой линейной формы \( L\in\gfq^{\textrm{hom}}[x_1,x_{2},\dotsc, x_k]_{1} \) определим множество
\[ Z(L)=\set{K\in \gfq^{\textrm{hom}}[x_1,x_2,\dotsc,x_{k}]_{1}}{Q=L\cdot K\in\ker\ell_{\gatr}}\subseteq\gfq^{\textrm{hom}}[x_1,x_2,\dotsc, x_k]_{1}.\]
Заметим, что \( Z(L) \)\nbsp{}--- линейное подпространство \( \gfq^{\textrm{hom}}[x_1,x_2,\dotsc,x_k]_{1} \).
Более того, существует взаимно однозначное соответствие (т.е. изоморфизм) между \( Z(L) \) и \( \cramped{\code^{\Supp{\widetilde{\ell}_{\gatr}(L)}}} \).
Оно устанавливается следующим утверждением, которое фактически следует из хода доказательства утверждения\nbsp{}[[prop:criteria-l]].

#+name: prop:isomorphism-zl
#+begin_proposition
Если \( L \)\nbsp{}--- линейная форма и \( T=\Supp{\widetilde{\ell}_{\gatr}(L)} \), то \( K\in \gfq^{\textrm{hom}}[x_1,x_2,\dotsc,x_k]_1 \) принадлежит \( Z(L) \), тогда и только тогда, когда \( \widetilde{\ell}_{\gatr}(K)\in \code^{T} \).
#+end_proposition

Из утверждения\nbsp{}[[prop:isomorphism-zl]] следует простой способ проверки того существует ли для данной линейной формы \( L \) такая линейная форма \( K\neq 0 \), что \( Q=L\cdot K\in \ker\ell_{\gatr} \).
Для этого следует вычислить размерность кода \( \cramped{\code^{\Supp{\widetilde{\ell}_{\gatr}(K)}}} \) и сравнить ее с нулем.
Если размерность этого кода не равна нулю, то такая \( K \) существует, а если она равна нулю, то таких \( K \) нет.

Из утверждения\nbsp{}[[prop:criteria-l]] в качестве следствия сформулируем ряд теорем.

#+name: thm:not-exists
#+begin_theorem
Ядро Шура--Адамара \( \ker\ell_{\gatr} \) кода \( \code \) не содержит квадратичные формы вид \( Q=L\cdot K\neq 0 \), если и только если носитель каждого кодового слова \( \code \) содержит информационное множество.
#+end_theorem

#+name: thm:exists-qforms
#+begin_theorem
Если \( \code \)\nbsp{}--- \( [n,k,d]_{q} \)-код и \( d < k \), то ядро Шура--Адамара \( \ker\ell_{\gatr} \) содержит квадратичные формы вида \( Q=L\cdot K\neq 0\).
#+end_theorem
#+begin_proof
Так как \( d<k \), то найдется кодовое слово, у которого носитель содержит меньше \( k \) элементов, поэтому носитель этого слова не может содержать информационное множество.
Значит из теоремы\nbsp{}[[thm:not-exists]] следует, что \( \ker\ell_{\gatr} \) для любой порождающей матрицы \( \gatr \) кода \( \code \) содержит квадратичную форму вида \( Q = L\cdot K\neq 0\).
#+end_proof

#+name: thm:exists-n-k
#+begin_theorem
Если длина \( n \) и размерность \( k \) линейного \( [n,k]_{q} \)-кода \( \code \) удовлетворяют неравенству \( n < 2k-1 \), то ядро Шура--Адамара \( \ker\ell_{\gatr} \) этого кода содержит хотя бы одну квадратичную форму \( Q\neq 0 \) вида \( Q=K\cdot L \).
#+end_theorem
#+begin_proof
Воспользуемся границей Синглтона.
Согласно утверждению\nbsp{}[[prop:singlton]] для любого \( [n,k,d]_{q} \)-кода \( \code \) справедливо неравенство \( d\le n-k+1. \)
Значит если \( n < 2k-1 \), то \( d\le n-k+1<2k-1-k+1=k. \)
И теперь, применяя теорему\nbsp{}[[thm:exists-qforms]], получим требуемое.
#+end_proof

В работе\nbsp{}[cite:@Couvreur_2023] (утверждение 10, стр.\nbsp{}16) говорится, что ядро Шура--Адамара случайного линейного кода \( \rode \) с порождающей матрицей \( R \) размерности \( k \) и длины \( n< 2k-1 \) в предположении, что матричный код квадратичных отношений \( \mcode_{R} \) имеет распределение весов, характерное для случайного матричного кода, c пренебрежимо малой вероятностью содержит квадратичные формы ранга не более, чем \( 2 \).
Аналогично, если \( n\le 3k-3 \), то там почти наверняка не будет квадратичных форм ранга не более, чем \( 3 \).
Однако это входит в противоречие с теоремой\nbsp{}[[thm:exists-n-k]], которое утверждает, что для таких параметров \( n \) и \( k \) в ядре Шура--Адамара любого кода содержится квадратичная форма ранга не выше, чем \( 2 \) (а значит и не выше, чем \( 3 \)).

В предположении корректности доказательства утверждения 10 из работы\nbsp{}[cite:@Couvreur_2023] противоречие может быть разрешено тем, что, вообще говоря, матричный код, построенный из квадратичных отношений для случайного линейного кода, не является случайным матричным кодом.
И различитель из\nbsp{}[cite:@Couvreur_2023] работает скорее для матричных кодов, чем в целом для линейных кодов, по крайней мере, в случае \( n<2k-1. \)

#+name: prop:no-quadratic
#+begin_proposition
Пусть код \( \code \) с порождающей матрицей \( \gatr \) является \( [n,k,d]_{q} \)-кодом и при этом \( d\ge k \).
Если дуальный код \( \dual{\code} \) имеет такое минимальное расстояние \( \dual{d} \), что \( \dual{d}\ge k \), то ядро \( \ker\ell_{\gatr} \) не содержит квадратичных форм \( Q\neq 0\) вида \( Q=K\cdot L  \), где \( K, L\in\gfq^{\textrm{hom}}[x_1,x_2,\dotsc,x_k]_{1} \).
#+end_proposition
#+begin_proof
Будем действовать от противного.
Пусть в \( \ker\ell_{\gatr} \) найдется такая квадратичная форма \(  Q\neq 0\), что \( Q=K\cdot L \).
Рассмотрим \( \cect = \widetilde{\ell}_{\gatr}(K) \).
Так как \( Q\neq 0 \), то и \( K\neq 0 \), поэтому и \( \cect\neq \vect[0] \).
Из утверждения\nbsp{}[[prop:criteria-l]] следует, что \( \Supp{\cect} \) не содержит информационного множества кода \( \code \).
По определению информационного множества это означает, что матрица \( \gatr\vert_{\Supp{\cect}} \) имеет ранг строго меньше \( k \).
Поэтому существует такой ненулевой вектор \( \vect\in \gfq^{|\Supp{\cect}|} \), что \( \gatr_{\Supp{\cect}}\cdot \tran{\vect} = \tran{\vect[0]}. \)
Более того, так как ранг \( \gatr\vert_{\Supp{\cect}} \) меньше или равен \( k-1 \), то в \( \gatr\vert_{\Supp{\cect}} \) найдется система из не более, чем \( k-1 \) столбца, ненулевая линейная комбинация которых равна \( 0 \), поэтому можно считать, что \( \wt{\vect}\le k-1 \).

По \( \vect \) построим \( \hect\in \gfq^{n} \) следующим образом: на множестве \(\Supp{\cect}\) он совпадает с \( \vect \), а все координаты не из \( \Supp{\cect} \) равны \( 0 \), т.е. \( \hect\vert_{\Supp{\cect}}=\vect \) и \( \hect_{\setminus \Supp{\cect}}=\vect[0]^{n-\wt{\cect}}. \)
С учетом выбора \( \vect \) и построения \( \hect \) выполняется цепочка равенств \( \gatr\cdot\tran{\hect}= \gatr\vert_{\Supp{\cect}}\cdot \tran{\vect} + \gatr\vert_{\nat\setminus \Supp{\cect}}\cdot \hect_{\setminus\Supp{\cect}}=\vect[0], \)
т.е. \( \hect\in\dual{\code}. \)

Теперь, так как \( \vect\neq \vect[0] \), то \( \hect\neq \vect[0] \).
Вес Хемминга ненулевого кодового слова \( \hect \) кода \( \dual{\code} \) не может быть меньше минимального расстояния \( \dual{\code} \), т.е. \( \dual{d} \), поэтому \( \wt{\hect}\ge \dual{d} \).
А значит \( \wt{\vect}=\wt{\hect}\ge \dual{d} \ge k \).
Но по построению \( \wt{\vect}\le k-1< k\), что невозможно.
Получено противоречие.
#+end_proof

Из границы Синглтона (утверждение\nbsp{}[[prop:singlton]]) следует, что минимальное расстояние \( \dual{d} \) кода, дуального к \( [n,k]_{q} \)-коду \( \code \), не превосходит \( n-(n-k)+1=k+1 \).
При этом коды, для которых \( d=n-k+1 \), называются МДР-кодами.
Получается, что из утверждения\nbsp{}[[prop:no-quadratic]] следует справедливость теоремы\nbsp{}.
#+name: thm:no-quadratic-mdr
#+begin_theorem
Если \( [n,k,d]_{q} \)-код \( \code \) дуален МДР-коду и при этом \( d\ge k \), то для порождающей матрицы \( \gatr \) кода \( \code \) ядро \( \ker\ell_{\gatr} \) не содержит квадратичных форм \( Q\neq 0 \) вида \( Q=K\cdot L \), здесь \( K,L \)\nbsp{}--- некоторые линейные формы.
#+end_theorem

#+name: prop:no-exists-dk
#+begin_proposition
Пусть \( L\in\gfq^{\textrm{hom}}[x_1,x_2,\dotsc, x_k]_{1} \) и \( \cect=\widetilde{\ell}_{\gatr}(L) \).
Тогда если для \( [n,k,d]_{q} \)-кода \( \code \) с порождающей матрицей \( \gatr \) существует такая линейная форма \( K\in\gfq^{\textrm{hom}}[x_{1},x_2,\dotsc, x_k]_{1} \), что \( K\neq 0 \) и \( Q=L\cdot K\in \ker\ell_{\gatr} \), то \( \wt{\cect}\le n-d \).
#+end_proposition
#+begin_proof
На основании утверждения\nbsp{}[[prop:criteria-l]] достаточно доказать, что \( \Supp{\cect} \) любого кодового слова \( \cect \) содержит информационное множество кода \( \code \).

Докажем, что вообще любое подмножество \( T\subseteq \nat \) мощности \( n-d+1 \) и выше содержит информационное множество.

Итак, пусть \( |T|\ge n-d+1 \).
Рассмотрим в \( \code \) два кодовых слова \( \cect_{1} \) и \( \cect_{2} \), которые совпадают на \( T \), т.е. для них выполнено равенство \( \cect\vert_{T}=\cect\vert_{T} \).
Тогда по построению \( \wt{\cect_1-\cect_2}\le n-|T| \).
Но в силу выбора \( T \) выполняется неравенство \( |T|\ge n-d+1 \), поэтому верно неравенство \( n-|T|\le d-1, \) значит \( \wt{\cect_1-\cect_2}\le d-1 <d \).
Так как \( \cect_{1} \) и \( \cect_{2} \) кодовые слова кода с минимальным расстоянием \( d \), то такое неравенство возможно только если \( \cect_{1}=\cect_{2} \).

Получается, что в коде нет различных кодовых слов, совпадающих на \( T \).
Но тогда из второй части утверждения\nbsp{}[[prop:inf-set]] следует, что \( T \) содержит информационное множество.
#+end_proof

Утверждение\nbsp{}[[prop:no-exists-dk]] можно обобщить, установив связь между размерностью пространства \( Z(L) \) и весом вектора \( \cect=\widetilde{\ell}_{\gatr}(L) \).
Для этого введем еще одно понятие.

#+name: def:gen-hamming-weight
#+begin_definition
Для произвольного \( [n,k]_{q} \)-кода \( \code \) и числа \( r\in \nat \) определим \( d_{r}(\code)\in\NN \) как минимальную мощность носителя всех \( [n,r]_{q} \)-подкодов \( \dode \) кода \( \code \), т.е.
\[ d_{r}\bydef \min\set{|\Supp{\dode}|:\ \dode\text{~--- подкод размерности } r\text{ кода } \code}. \]
Число \( d_{r}(\code) \) называется обобщенным \( r \)-тым расстоянием Хемминга кода \( \code \).
#+end_definition

Ясно, что \( d_{1}=d \)\nbsp{}--- минимальное расстояние кода \( \code \).

Обобщенное расстояние Хемминга линейных кодов впервые введено в работе\nbsp{}[cite:@wei1991].
В той же работе доказано следующее утверждение, которое является естественным обобщением границы Синглтона.

# #+attr_latex: :options [см.~\cite{wei1991}]
#+name: prop:gen-singltone
#+begin_proposition
Для любого \( [n,k]_{q} \)-кода \( \code \) и любого \( r\in\nat \) справедливо неравенство \( d_{r}\le n-k+r \).
#+end_proposition

Используя утверждение\nbsp{}[[prop:gen-singltone]], докажем следующее утверждение

#+name: prop:gen-weight-zk
#+begin_proposition
Пусть \( L\in\gfq^{\textrm{hom}}[x_1,x_2,\dotsc, x_k]_{1} \) и \( \cect=\widetilde{\ell}_{\gatr}(L) \).
Тогда если для \( [n,k]_{q} \)-кода \( \code \) с порождающей матрицей \( \gatr \) выполняется неравенство \( \dim Z_{\gatr}(L)\ge r \), то \( \wt{\cect}\le n-d_{r}(\code) \).
#+end_proposition
#+begin_proof
По условию \( Z_{\gatr}(L) \) содержит \( r \) линейно независимых линейных форм \( K_1,K_2,\dotsc,K_{r}\in\gfq^{\textrm{hom}}[x_1,x_2,\dotsc,x_k]_{1} \).
Пусть \( T=\Supp{\widetilde{\ell}_{\gatr}(K)} \).
Из утверждения\nbsp{}[[prop:isomorphism-zl]] линейная форма \( K_{i} \), \( i=1,2,\dotsc,r \), принадлежит \( Z_{\gatr}(L) \), если и только если \( \cect_{i}=\widetilde{\ell}_{\gatr}(K_{i})\in\code^{T}. \)

Заметим, что \( \cect_{1},\cect_{2},\dotsc,\cect_{r} \) линейно независимы.
Если бы это было не так, то существовал бы набор \( a_1,a_2,\ldots,a_{r}\in\gfq \), в котором существует хотя бы один ненулевой элемент, что линейная форма \( K=\sum_{i=1}^{r}a_{i}K_{i}=b_{1}x_{1}+b_{2}x_{2}+\dotsb+b_{k}x_{k} \) на столбцах матрицы \( \gatr \) обращается в ноль.
Но \( K(\gatr)=\sequence{b_{1}b_{2}\dotsc b_{k}}\cdot \gatr = \boldsymbol{0}^{n} \), а так как \( \gatr \) имеет ранг \( k \) как порождающая матрица \( [n,k]_{q} \)-кода, то отсюда следует, что \( b_{1}=b_{2}=\dotsb=b_{k}=0 \) и поэтому \( K\equiv 0 \), что противоречит линейной независимости \( K_{1},K_{2},\dotsc, K_{r} \).

Итак, код \( \code^{T} \), с одной стороны, является подкодом кода \( \code \), а с другой имеет размерность по меньшей мере \( r \).
Рассмотрим \( \dode \)\nbsp{}--- произвольный подкод кода \( \code^{T} \) размерности \( r \).
По определению обобщенного расстояния Хемминга \( d_{r} \) должно выполняться неравенство \( d_{r}\le |\Supp{\dode}| \).
Но \( \Supp{\dode}\subseteq\Supp{\code^{T}} \), поэтому \( d_{r}\le |\Supp{\code^{T}}|\).

Но \( |\Supp{\code^{T}}|\le n-|T| \), а значит должно выполняться неравенство \( d_{r}\le n-|T| \).
Осталось заметить, что по построению \( |T|=|\Supp{\widetilde{\ell}_{\gatr}(K)}|=\wt{\widetilde{\ell}_{\gatr}(K)}=\wt{\cect} \).
#+end_proof
