* Введение \( \supp{X} \)
Криптосистема Мак-Элиса\nbsp{}--- одна из старейших криптосистем с открытым ключом.
Она была предложена в 1978 Р. Дж. Мак-Элисом\nbsp{}[cite:@j.mceliece1978].
Данная криптосистема основывается на \(\npol\)-трудной
проблеме в теории кодирования. Основная идея её построения состоит в
маскировке некоторого кода, имеющего эффективные алгоритмы
декодирования, под код, не обладающий видимой алгебраической и
комбинаторной структурой, такие коды принято называть кодами общего
положения. Эта криптосистема обладает одним важным преимуществом\nbsp{}---
высокой скоростью зашифрования и расшифрования. Однако, у неё имеется
серьёзный недостаток\nbsp{}--- относительно низкая скорость передачи (\(R\)).
Обычно у кодовых криптосистем \(R<1\), тогда как у криптосистемы RSA
скорость в точности равна \(1\).

В этой работе рассматривается обобщение криптосистемы Мак-Элиса,
предложенное в 1994 году В.\nbsp{}М.\nbsp{}Сидельниковым\nbsp{}[cite:@sidelnikov1994].
В этой работе модификация, предложенная В. М. Сидельниковым, называется
криптосистемой Мак-Элиса--Сидельникова.

Криптосистема Мак-Элиса--Сидельникова строится на основе \(u\)-кратного использования кодов Рида--Маллера \(\RM(r,m)\).
Она имеет высокую криптографическую стойкость, скорость передачи близкую к \(1\) и сравнительно невысокую сложность шифрования секретных
сообщений и расшифрования криптограмм этих сообщений.

В работе исследуются вопросы, связанные с пространством
эквивалентных секретных ключей, то есть секретных ключей,
порождающих одинаковые открытые ключи, новой криптосистемы.

* Теорема Пифагора                                                  :algebra:

Линейным кодом \( \code \) называется произвольное подпространство пространства \( \vecspace_{n}(q) \).

Это код \( \dualcode*{\RM(r,m)} \), дуальный к коду Рида--Маллера \( \RM(r,m) \).

Матрица \( \transpose{G} \) и \( \transpose*{A\cdot G} \)\nbsp{}--- транспонированные матрицы \( G \) и \( A\cdot G \) соответственно.

Пусть \(\code\)\nbsp{}--- некоторый линейный код с параметрами
\([n,k,d]\) над конечным полем \(\GF{q}\), который имеет эффективные
алгоритмы декодирования, \(G\)\nbsp{}--- его порождающая матрица размера \(k\times n\), \(H\)\nbsp{}--- невырожденная \(k\times k\) матрица и \(\Gamma\)\nbsp{}--- /перестановочная матрица/ размера \(n\times n\).

/Секретным ключом/ в данной схеме является тройка \((H,G,\Gamma)\), а *открытым ключом*\nbsp{}--- матрица \(G'=H\cdot G\cdot \Gamma\).

#+NAME: def:triangle
#+begin_definition
*Прямоугольным треугольником* называется треугольник, у
  которого один угол равен \(90^{\circ}\).
#+end_definition

#+begin_definition*
*Прямоугольным треугольником* называется треугольник, у
  которого один угол равен 90 градусам.
#+end_definition*

#+NAME: rem:numbered
#+begin_remark
*Кодом Рида--Маллера* \(\RM(r,m)\), называется множество векторов
значений \(\Omega_f\) всех булевых функций \(f(y_1,\ldots,y_m)\),
степень нелинейности (максимальная длина монома, входящего в полином
Жегалкина функции \(f\)) которых не превосходит \(r\), то есть
\[\begin{multlined}
\RM(r,m)=\biggl\{\Omega_f=(x_1,\ldots,x_n),
n=2^m|\ f(y_1,\ldots,y_m)=\\
=a_0\oplus\bigoplus_{s=1}^{t}\bigoplus_{1\le
i_1<\ldots<i_s\leqslant m}a_{i_1,\ldots,i_s}y_{i_1}\ldots
y_{i_s},\;t\leqslant r\biggr\}
\end{multlined}\]
#+end_remark

Далее рассмотрим замечание, которое не имеет номера.

#+begin_remark*
Два секретных ключа \((H',G,\Gamma')\) и \((H'',G,\Gamma'')\) назовем
/эквивалентными/, если и только если выполняется соотношение
\[H'\cdot G\cdot\Gamma'=H''\cdot G\cdot\Gamma'',\]
то есть порождаемые ими открытые ключи совпадают.
#+end_remark*

Теперь докажем интересное утверждение.

#+NAME: prop:d-rm
#+begin_proposition
Пусть кодовое расстояние кода \(\dualcode{\code}\), дуального к коду
\(\code\), строго больше двух.
Тогда для любой матрицы \(A\in \GL_{k}(\GF{q})\), принадлежащей множеству \(\mathrm{A}(\code)\), существует и единственная перестановка \(\Gamma\) из группы
автоморфизмов \(\paut{\code}\).
И для любой перестановки \(\Gamma\in \paut{\code}\) существует и единственная матрица \(A\in\mathrm{A}(\code)\).
#+end_proposition
#+begin_proof
Пусть \(A\) принадлежит \(\mathrm{A}(\code)\), тогда найдется
перестановка \(\Gamma\) такая, что \[AG=G\Gamma.\]
Очевидно, что \(\Gamma\in \paut{\code}\).
Докажем, что такая \(\Gamma\) единственна.
Пусть существуют две перестановки \(\Gamma'\) и \(\Gamma''\) такие, что \[AG=G\Gamma'\;\;\;AG=G\Gamma''.\]
Тогда \[G\Gamma'\Gamma''^{-1}=G.\]
В силу того, что кодовое расстояние \(\mathcal C^{\perp}\) строго больше двух, то в матрице \(G\) нет двух
одинаковых столбцов.
Поэтому из последнего соотношения следует, что
\[\Gamma'\Gamma''^{-1}=E.\]
Полученное соотношение, означает, что \(\Gamma'=\Gamma''\).

Докажем, что для \(\Gamma\in \paut{\code}\) найдётся единственная матрица \(A\in \mathrm{A}(\code).\)
В силу того, что \(\Gamma\in \paut{\code}\), то существует \(A\), с которой \[AG=G\Gamma.\]
Понятно, что \(A\in\mathrm{A}(\code)\).
Если найдутся две матрицы \(A'\) и \(A''\) такие, что \[A'G=G\Gamma\;\;A''G=G\Gamma,\] то
\(A'G=A''G\).
Ранг матрицы \(G\) равен \(k\), поэтому \(A'=A''\).
#+end_proof

#+begin_proposition*
Пусть в качестве порождающей матрицы кода \(\code\) в криптосистеме Мак-Элиса взята матрица \(G\).
Тогда существует взаимно однозначное соответствие между множеством \(
\paut{\code}\) и классом эквивалентности \([(H,G,\Gamma)]\) множества секретных ключей криптосистемы Мак-Элиса.
#+end_proposition*

Из этого утверждения немедленно получаем формулу для мощности
множества открытых ключей, которая совпадает с числом классов
эквивалентности секретных ключей.

#+NAME: ex:myexample
#+begin_example0
Пусть \(\mathcal E\)\nbsp{}--- множество всех открытых ключей криптосистемы Мак--Элиса.
Тогда справедлива формула
\[|\mathcal E|=\frac{n!h_k(q)}{|\paut{\code}|},\]
здесь \(h_k(q)=|\GL_k(\GF{q})|=(q^k-1)(q^k-q)\ldots (q^k-q^{k-1})\)\nbsp{}--- число невырожденных матриц порядка \(k\) над полем \(\GF{q}\).
#+end_example0

А вот ссылка на \href{https://ru.wikipedia.org}{википедию}.
Тоже самое, но в окружении без номера.

#+begin_example*
Пусть \(\mathcal E\)\nbsp{}--- множество всех открытых ключей криптосистемы Мак--Элиса.
Тогда справедлива формула
\[|\mathcal E|=\frac{n!h_k(q)}{|\paut{\code}|},\]
здесь \(h_k(q)=|\GL_k(\GF{q})|=(q^k-1)(q^k-q)\ldots (q^k-q^{k-1})\)\nbsp{}--- число невырожденных матриц порядка \(k\) над полем \(\GF{q}\).
#+end_example*

#+NAME: cor:rm-keys
#+begin_corollary
Общее число открытых ключей в криптосистеме Мак-Элиса, в которой в
качестве матрицы \(G\) была выбрана порождающая матрица двоичного
кода Рида--Маллера, вычисляется по формуле
\[ |\mathcal E|=\frac{n!h_k}{2^mh_m},\]
здесь \(h_k=h_k(2)\) и \(h_m=h_m(2)\).
#+end_corollary

#+begin_theorem*
Сумма квадратов катетов равна квадрату гипотенузы, т.е.
#+NAME: eq:thm-pif
\begin{equation}
    a^2+b^2=c^2.
\end{equation}
#+end_theorem*
#+begin_proof
Доказательство очень простое и все его знают со школьных времен.
#+end_proof

Множество решений уравнения\nbsp{}[[eq:thm-pif]] называется пифагоровыми тройками.
Обозначим их символом \(\mathcal{P}\) (каллиграфическое \(P\).
Очевидно, что \(\mathcal{P}\subseteq \mathbb{R}^{3}\).

/Курсивный шрифт/.
*Жирный шрифт*.
/*Курсивный жирный шрифт*/.

Выясним некоторые свойства множества \(\mathcal L(H_1,\ldots,H_u)\).
Обозначим через\\
\(\mathrm{A}(\RM(r,m))\) множество матриц, которые задают перестановки,
принадлежащие группе автоморфизмов кода \(\RM(r,m)\) с порождающей
матрицей \(R\), то есть
\[\mathrm{A}(\RM(r,m))=\{A|\exists \Gamma\in \paut{\RM(r,m)}:
A\cdot R=R\cdot \Gamma\}.\]

#+NAME: lem:numbered
#+begin_lemma
Пусть кортеж \((A_1,\ldots,A_u)\) принадлежит множеству \[\mathcal{L}(H_1,\ldots,H_u).\]
Тогда для любых матриц \(D_1,\ldots,D_u\in \mathrm{A}(\RM(r,m))\) и любой перестановки \(\Gamma\in S_u\) кортеж
\[(A_{\Gamma(1)}D_1,\ldots,A_{\Gamma(u)}D_u)\] также принадлежит
множеству \(\mathcal L(H_1,\ldots,H_u)\).
#+end_lemma

#+begin_lemma*
Это лемма без номера.

Пусть кортеж \((A_1,\ldots,A_u)\) принадлежит множеству\\
\(\mathcal{L}(H_1,\ldots,H_u)\).
Тогда для любых матриц \(D_1,\ldots,D_u\in
\mathcal A(RM(r,m))\) и любой перестановки \(\Gamma\in S_u\) кортеж
\[(A_{\Gamma(1)}D_1,\ldots,A_{\Gamma(u)}D_u)\] также принадлежит
множеству \(\mathcal L(H_1,\ldots,H_u)\).
#+end_lemma*

#+NAME: thm:withlemm
#+begin_theorem
Это теорема, в доказательстве которой содержится лемма.
#+end_theorem
#+begin_proof
Доказательство разобъем на несколько лемм.

#+NAME: lem:example:in-1
#+begin_lemma
Это первая внутренняя лемма.
#+end_lemma

Вторая лемма.

#+NAME: lem:example:in-2
#+begin_lemma
Это вторая внутренняя лемма.
#+end_lemma

#+NAME: lem:example:in-3
#+begin_lemma
Это третья внутренняя лемма.
#+end_lemma

Наконец, можно завершить доказательство теоремы, применив к лемме\nbsp{}[[lem:example:in-3]] леммы\nbsp{}[[lem:example:in-1]] и\nbsp{}[[lem:example:in-2]].

#+end_proof


* Примеры различных окружений
:PROPERTIES:
:CUSTOM_ID: sec:ref-to-articles
:END:

#+NAME: def:001
#+begin_definition
  Это определение.
#+end_definition

#+begin_definition*
  Это определение.
#+end_definition*

#+NAME: rem:001
#+begin_remark
  Это замечание.
#+end_remark

#+begin_remark*
  Это замечание.
#+end_remark*

#+NAME: ex:001
#+begin_example0
  Это пример.
#+end_example0

#+begin_example*
  Это пример.
#+end_example*

#+NAME: task:001
#+begin_task
  Это задача.
#+end_task

#+begin_task*
  Это задача.
#+end_task*

#+NAME: exer:001
#+begin_exercise
Это упражнение.
#+end_exercise

#+begin_exercise*
Это упражнение.
#+end_exercise*

#+NAME: prob:001
#+begin_problem
Это проблема.
#+end_problem

#+begin_problem*
Это проблема.
#+end_problem*

#+NAME: ques:001
#+begin_question
Это вопрос.
#+end_question

#+begin_question*
Это вопрос.
#+end_question*

#+NAME: thm:001
#+begin_theorem
Это теорема.
#+end_theorem

#+begin_theorem*
Это теорема.
#+end_theorem*

#+NAME: prop:001
#+begin_proposition
Это утверждение (или предложение).
#+end_proposition

#+begin_proposition*
Это утверждение (или предложение).
#+end_proposition*

#+NAME: ass:001
#+begin_assertion
Это утверждение.
#+end_assertion

#+begin_assertion*
Это утверждение.
#+end_assertion*

#+NAME: cor:001
#+begin_corollary
Это следствие.
#+end_corollary

#+begin_corollary*
Это следствие.
#+end_corollary*

#+NAME: lem:001
#+begin_lemma
Это лемма.
#+end_lemma

#+begin_lemma*
Это лемма без номера.
#+end_lemma*

А это ссылки:

- Раздел\nbsp{}[[#sec:ref-to-articles]]
- Определение\nbsp{}[[def:001]]
- Замечание\nbsp{}[[rem:001]]
- Пример\nbsp{}[[ex:001]]
- Задача\nbsp{}[[task:001]]
- Упражнение\nbsp{}[[exer:001]]
- Проблема\nbsp{}[[prob:001]]
- Вопрос\nbsp{}[[ques:001]]
- Теорема\nbsp{}[[thm:001]]
- Утверждение (предложение)\nbsp{}[[prop:001]]
- Утверждение\nbsp{}[[ass:001]]
- Лемма\nbsp{}[[lem:001]]
- Следствие\nbsp{}[[cor:001]]
